Improved updater

diff --git a/update b/update
--- a/update
+++ b/update
@@ -10,17 +10,17 @@
 #
 
 
-echo -n "Checking for updates: "
+echo -n 'Checking for updates: '
 exit_code=0
 
-if [ -d "$(dirname $(readlink -f $0))/.git" ]; then
-	( which git >/dev/null ) \
-	|| ( echo 'Nothing to do (git not found)' ) \
-	&& (
-		git pull | grep 'Unpacking objects'
-		exit_code=$( if [ "$?" -eq "0" ]; then echo 1; else echo 0; fi ) # exit_code = 0 if nothing happened, exit_code = 1 if we updated
+if [ -d "$(dirname $(readlink -f $0))/.git" ]; then # we have a ".git" directory
+	if [ "$(which git 2>&1 >/dev/null ; echo $?)" -eq "0" ]; then # we have the git application
+		git pull | grep 'files changed' | grep 'insertions' | grep 'deletions'
+		exit_code=$( if [ "$?" -eq "0" ]; then echo -n 1; else echo -n 0; fi ) # = 0 if nothing happened, = 1 if we updated
 		[ "$exit_code" -ne "0" ] && ( echo '# WARNING: Please review the license file before continuing. The terms and conditions may have changed since the last update!' )
-	)
+	else
+		echo 'Nothing to do (git not found)'
+	fi
 else
 	echo 'Local git repository not found'
 fi
